name: Patch-Apply Test on OpenCCU Nightly

on:
  push:
  schedule:
    - cron: '0 6 * * *' # run at 7am UTC
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y dos2unix jq curl wget

      - name: Checkout 🚚
        uses: actions/checkout@v2

      - name: Run tests 🩺
        run: ./snapshot-test.sh
